# Generated by Django 5.0.1 on 2024-01-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.CharField(choices=[('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('Coxbazar', 'Coxbazar')], max_length=20)),
                ('arrival_station', models.CharField(choices=[('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('Coxbazar', 'Coxbazar')], max_length=20)),
                ('departure_time', models.CharField(choices=[('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('011:00 AM', '11:00 AM'), ('01:00 PM', '01:00 PM'), ('03:00 PM', '03:00 PM'), ('05:00 PM', '05:00 PM'), ('08:00 PM', '08:00 PM'), ('11:00 PM', '11:00 PM')], max_length=20)),
                ('available_seats', models.IntegerField(default=30)),
                ('date_of_journey', models.DateField()),
                ('ticket_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seat', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train'),
        ),
    ]
