# Generated by Django 5.0.1 on 2024-01-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trains.schedule')),
            ],
        ),
    ]
